// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package util

import (
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"math/rand"
	"net/netip"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/openconfig/gribigo/fluent"

	"github.com/openconfig/lemming/gnmi/fakedevice"
)

// ScaleProfileConfig defines the parameters for generating gRIBI entries for a specific scale profile.
type ScaleProfileConfig struct {
	// Common parameters
	AddrFamily              string // "ipv6"
	NumNetworkInstances     int    // Number of network instances to generate (e.g., 1 or 1024)
	NetworkInstanceBaseName string // Base name for network instances (e.g., "DEFAULT" or "VRF"). NI names will be "base-1", "base-2", etc.
	NumPrefixes             int    // Total number of IP prefixes (AFT entries) to generate
	NumNexthopGroup         int    // Total number of Next Hop Groups (NHGs) to generate
	NumNexthopPerNHG        int    // Number of Next Hops (NHs) per NHG

	// Prefix generation details
	PrefixStart string // Starting IP prefix (e.g., "10.5.1.1/32" or "2001:aa:bb::1/128")

	// MPLS Label details
	UseSameMPLSLabel bool   // If true, all NHs use MPLSLabelStart. If false, labels increment.
	MPLSLabelStart   uint64 // Starting MPLS label value

	// Encapheader Configs
	UDPSrcPort uint64
	UDPDstPort uint64
	SrcIP      string
	DstIPStart string
	NumDstIP   int
	DSCP       uint64
	IPTTL      uint64

	// The IP address of the ATE interface on the egress link.
	EgressATEIPv6 string // e.g., atePort2.IPv6
}

// GetFirstAddrFromPrefix takes a CIDR string (e.g., "2001:aa:bb::/48")
// and returns the first usable address as a string (e.g., "2001:aa:bb::").
func GetFirstAddrFromPrefix(cidr string) (string, error) {
	prefix, err := netip.ParsePrefix(cidr)
	if err != nil {
		return "", fmt.Errorf("failed to parse prefix %q: %w", cidr, err)
	}
	// For a prefix, Addr() returns the network address itself, which is the first address.
	return prefix.Addr().String(), nil
}

// GeneratePrefix calculates the specific prefix string based on a start prefix and an index offset.
func GeneratePrefix(startPrefixCIDR string, index int) (string, error) {
	startPrefix, err := netip.ParsePrefix(startPrefixCIDR)
	if err != nil {
		return "", fmt.Errorf("failed to parse start prefix %q: %w", startPrefixCIDR, err)
	}
	startAddr := startPrefix.Addr()

	currentAddr := startAddr
	for i := 0; i < index; i++ {
		nextAddr := currentAddr.Next()
		if !nextAddr.IsValid() || !startPrefix.Contains(nextAddr) {
			return "", fmt.Errorf("ran out of valid IP addresses after generating %d prefixes, starting from %s", i+1, startAddr)
		}
		currentAddr = nextAddr
	}

	// Assume generated prefixes are host routes
	var generatedPrefixLen int
	if currentAddr.Is6() {
		generatedPrefixLen = 128
	} else if currentAddr.Is4() {
		generatedPrefixLen = 32
	} else {
		return "", fmt.Errorf("invalid start address type: %s", startAddr)
	}

	prefix := netip.PrefixFrom(currentAddr, generatedPrefixLen)
	return prefix.String(), nil
}

// FormatMPLSHeader formats MPLS header bytes for logging.
func FormatMPLSHeader(data []byte) string {
	if len(data) < 4 {
		return fmt.Sprintf("Invalid MPLS data (len < 4): % X", data)
	}

	headerValue := binary.BigEndian.Uint32(data[:4])

	label := (headerValue >> 12) & 0xFFFFF
	exp := uint8((headerValue >> 9) & 0x07)
	s := (headerValue >> 8) & 0x01
	ttl := uint8(headerValue & 0xFF)

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("MPLS Label: %d, ", label))
	sb.WriteString(fmt.Sprintf("EXP: %d, ", exp))
	sb.WriteString(fmt.Sprintf("BoS: %t, ", s == 1))
	sb.WriteString(fmt.Sprintf("TTL: %d", ttl))

	if len(data) > 4 {
		sb.WriteString(fmt.Sprintf(", Payload: % X", data[4:]))
	}

	return sb.String()
}

// MPLSLabelToPacketBytes converts an MPLS label (as uint32) into its 4-byte wire representation.
// Assumes default EXP=0, BoS=1, TTL=255 for the generated bytes.
func MPLSLabelToPacketBytes(label uint32) []byte {
	buf := make([]byte, 4)
	// Label (20 bits) << 12 | EXP (3 bits) << 9 | BoS (1 bit) << 8 | TTL (8 bits)
	// Example: Label 100, EXP 0, BoS 1, TTL 255
	// (100 << 12) | (0 << 9) | (1 << 8) | 255 = 0x000641FF
	headerValue := (label << 12) | (1 << 8) | 255 // Set BoS=1, TTL=255
	binary.BigEndian.PutUint32(buf, headerValue)
	return buf
}

// populateNextHops generates NextHop entries for a specific network instance.
// nhIndexOffset ensures global uniqueness of NH indices across NIs.
// niIndex is the 0-based index of the network instance being populated.
func (cfg *ScaleProfileConfig) populateNextHops(niIndex int, numNHsThisNI int, nhIndexOffset uint64) ([]fluent.GRIBIEntry, error) {
	entries := []fluent.GRIBIEntry{}
	if numNHsThisNI <= 0 {
		return entries, nil
	}

	// Generate Destination IPs for Encap Header
	dstIPs := []string{}
	if cfg.NumDstIP > 0 {
		startDstIP, err := netip.ParseAddr(cfg.DstIPStart)
		if err != nil {
			return nil, fmt.Errorf("failed to parse DstIPStart %q: %w", cfg.DstIPStart, err)
		}
		currentDstIP := startDstIP
		for i := 0; i < cfg.NumDstIP; i++ {
			if !currentDstIP.IsValid() {
				return nil, fmt.Errorf("ran out of valid destination IP addresses starting from %s after %d IPs", cfg.DstIPStart, i)
			}
			dstIPs = append(dstIPs, currentDstIP.String())
			currentDstIP = currentDstIP.Next()
		}
	} else {
		return nil, errors.New("NumDstIP must be positive to generate destination IPs")
	}

	for i := 1; i <= numNHsThisNI; i++ {
		globalNHIndex := nhIndexOffset + uint64(i)
		mplsLabel := cfg.MPLSLabelStart
		if !cfg.UseSameMPLSLabel {
			// Assign label based on the VRF index for unique label per VRF profiles
			mplsLabel = cfg.MPLSLabelStart + uint64(niIndex)
		}

		nhEntry := fluent.NextHopEntry().
			WithNetworkInstance(fakedevice.DefaultNetworkInstance).
			WithIndex(globalNHIndex).
			WithIPAddress(cfg.EgressATEIPv6).
			AddEncapHeader(
				fluent.MPLSEncapHeader().WithLabels(mplsLabel),
				fluent.UDPV6EncapHeader().
					WithDstUDPPort(cfg.UDPDstPort).
					WithSrcUDPPort(cfg.UDPSrcPort).
					WithSrcIP(cfg.SrcIP).
					WithDstIP(dstIPs[(int(globalNHIndex)-1)%cfg.NumDstIP]).
					WithDSCP(cfg.DSCP).
					WithIPTTL(cfg.IPTTL),
			)

		entries = append(entries, nhEntry)
	}
	return entries, nil
}

// combinationKey generates a unique, sorted string key for a slice of NH indices.
func combinationKey(indices []uint64) string {
	sort.Slice(indices, func(i, j int) bool { return indices[i] < indices[j] })

	var sb strings.Builder
	for i, idx := range indices {
		sb.WriteString(strconv.FormatUint(idx, 10))
		if i < len(indices)-1 {
			sb.WriteString(",")
		}
	}
	return sb.String()
}

// populateNextHopGroups generates NextHopGroup entries for a specific network instance.
// nhgIDOffset ensures global uniqueness of NHG IDs across NIs.
// nhIndexOffset is needed to correctly reference the globally unique NH indices.
func (cfg *ScaleProfileConfig) populateNextHopGroups(numNHGsThisNI int, numNHsPerGroup int, nhgIDOffset uint64, nhIndexOffset uint64) ([]fluent.GRIBIEntry, error) {
	numNHsThisNI := cfg.NumNexthopPerNHG * cfg.NumNexthopGroup
	k := cfg.NumNexthopPerNHG
	entries := []fluent.GRIBIEntry{}

	if numNHGsThisNI <= 0 {
		return entries, nil
	}

	// 1. Create a slice of available NH indices *for this NI* (using global offset)
	niNHIndices := make([]uint64, numNHsThisNI)
	for i := 0; i < numNHsThisNI; i++ {
		niNHIndices[i] = nhIndexOffset + uint64(i+1)
	}

	// 2. Shuffle the indices randomly (within this NI's pool)
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	r.Shuffle(len(niNHIndices), func(i, j int) {
		niNHIndices[i], niNHIndices[j] = niNHIndices[j], niNHIndices[i]
	})

	// 3. Assign indices ensuring unique combinations *within this NI*
	usedCombinations := make(map[string]bool)

	for localNHGIdx := uint64(1); localNHGIdx <= uint64(numNHGsThisNI); localNHGIdx++ {
		globalNHGId := nhgIDOffset + localNHGIdx
		foundCombination := false
		for comboStartIndex := 0; comboStartIndex+k <= numNHsThisNI; comboStartIndex++ {
			indSlice := make([]uint64, k)
			copy(indSlice, niNHIndices[comboStartIndex:comboStartIndex+k])

			key := combinationKey(indSlice)

			if !usedCombinations[key] {
				usedCombinations[key] = true
				nhgEntry := fluent.NextHopGroupEntry().
					WithNetworkInstance(fakedevice.DefaultNetworkInstance).
					WithID(globalNHGId)

				for _, nhIndex := range niNHIndices[comboStartIndex : comboStartIndex+k] {
					nhgEntry.AddNextHop(nhIndex, 1)
				}
				entries = append(entries, nhgEntry)

				foundCombination = true
				break
			}

		}

		if !foundCombination {
			return nil, fmt.Errorf("failed to find unique NH combination for NI %s, NHG local index %d (global ID %d). (n=%d, k=%d, groups=%d)", fakedevice.DefaultNetworkInstance, localNHGIdx, globalNHGId, numNHsThisNI, k, numNHGsThisNI)
		}
	}

	return entries, nil
}

// populatePrefixes generates IPv4 or IPv6 entries for a specific network instance.
// nhgIDOffset is needed to correctly reference the globally unique NHG IDs.
// numPrefixesThisNI specifies how many prefixes to generate for this specific NI.
// numNHGsPerNI is needed for the modulo calculation to map prefixes to NHGs within this NI.
func (cfg *ScaleProfileConfig) populatePrefixes(niName string, numPrefixesThisNI int, numNHGsPerNI int, nhgIDOffset uint64) ([]fluent.GRIBIEntry, error) {
	entries := []fluent.GRIBIEntry{}

	for i := 0; i < numPrefixesThisNI; i++ {
		// Generate prefix based on index 'i' *within this NI*.
		// This achieves reuse as index 'i' repeats for each NI.
		prefixStr, err := GeneratePrefix(cfg.PrefixStart, i)
		if err != nil {
			return nil, fmt.Errorf("failed to generate prefix at index %d for NI %s: %w", i, niName, err)
		}

		// Map prefix to a local NHG index within this NI using modulo.
		localNHGIndex := uint64(i%numNHGsPerNI + 1)
		globalNHGId := nhgIDOffset + localNHGIndex // Calculate the global NHG ID

		var entry fluent.GRIBIEntry
		switch cfg.AddrFamily {
		case "ipv6":
			entry = fluent.IPv6Entry().
				WithNetworkInstance(niName).
				WithPrefix(prefixStr).
				WithNextHopGroup(globalNHGId).
				WithNextHopGroupNetworkInstance(fakedevice.DefaultNetworkInstance)
		case "ipv4":
			return nil, fmt.Errorf("ipv4 entry generation not yet implemented")
		default:
			return nil, fmt.Errorf("internal error: unsupported AddrFamily %q", cfg.AddrFamily)
		}
		entries = append(entries, entry)
	}

	return entries, nil
}

// GenerateScaleProfileEntries randomly generates fluent gRIBI entries based on ScaleProfileConfig in one network instance.
func GenerateScaleProfileEntries(ctx context.Context, cfg *ScaleProfileConfig) ([]fluent.GRIBIEntry, error) {
	// 1. Validation of the parameters.
	if cfg.NumNetworkInstances <= 0 {
		return nil, errors.New("NumNetworkInstances must be positive")
	}
	if cfg.NetworkInstanceBaseName == "" {
		return nil, errors.New("NetworkInstanceBaseName must be provided")
	}
	if cfg.NumPrefixes <= 0 {
		return nil, errors.New("NumPrefixes must be positive")
	}
	if cfg.NumNexthopGroup <= 0 {
		return nil, errors.New("NumNexthopGroup must be positive")
	}
	if cfg.NumNexthopPerNHG <= 0 {
		return nil, errors.New("NumNexthopPerNHG must be positive")
	}
	if cfg.AddrFamily != "ipv6" {
		// TODO: Support ipv4 when fluent.UDPV4EncapHeader is available
		return nil, fmt.Errorf("invalid AddrFamily: %q, must be 'ipv6'", cfg.AddrFamily)
	}
	prefixAddr, err := netip.ParsePrefix(cfg.PrefixStart)
	if err != nil {
		return nil, fmt.Errorf("invalid PrefixStart %q: %w", cfg.PrefixStart, err)
	}
	if cfg.AddrFamily == "ipv6" && !prefixAddr.Addr().Is6() {
		return nil, fmt.Errorf("AddrFamily %q does not match PrefixStart %q", cfg.AddrFamily, cfg.PrefixStart)
	}
	if cfg.SrcIP == "" {
		return nil, errors.New("SrcIP for encapsulation must be provided")
	}
	if cfg.DstIPStart == "" {
		return nil, errors.New("DstIPStart for encapsulation must be provided")
	}
	if cfg.NumDstIP <= 0 {
		return nil, errors.New("NumDstIP must be positive")
	}
	_, err = netip.ParseAddr(cfg.DstIPStart)
	if err != nil {
		return nil, fmt.Errorf("invalid DstIPStart %q: %w", cfg.DstIPStart, err)
	}
	if cfg.EgressATEIPv6 == "" {
		return nil, errors.New("EgressATEIPv6 must be provided in ScaleProfileConfig")
	}
	if _, err := netip.ParseAddr(cfg.EgressATEIPv6); err != nil {
		return nil, fmt.Errorf("invalid EgressATEIPv6 %q: %w", cfg.EgressATEIPv6, err)
	}
	if cfg.NumNetworkInstances > 1 && cfg.NetworkInstanceBaseName == fakedevice.DefaultNetworkInstance {
		return nil, fmt.Errorf("cannot use default NI name %q as base when NumNetworkInstances > 1", fakedevice.DefaultNetworkInstance)
	}
	if !cfg.UseSameMPLSLabel && cfg.NumNetworkInstances > 1 && (cfg.MPLSLabelStart+uint64(cfg.NumNetworkInstances) > (1 << 20)) {
		// Check if MPLS labels might exceed 20-bit limit
		return nil, fmt.Errorf("MPLS label range might exceed 20 bits with %d instances starting from %d", cfg.NumNetworkInstances, cfg.MPLSLabelStart)
	}
	// Ensure total counts are divisible or handle remainders if necessary
	if cfg.NumPrefixes%cfg.NumNetworkInstances != 0 {
		return nil, fmt.Errorf("total NumPrefixes (%d) must be divisible by NumNetworkInstances (%d)", cfg.NumPrefixes, cfg.NumNetworkInstances)
	}
	if cfg.NumNexthopGroup%cfg.NumNetworkInstances != 0 {
		return nil, fmt.Errorf("total NumNexthopGroup (%d) must be divisible by NumNetworkInstances (%d)", cfg.NumNexthopGroup, cfg.NumNetworkInstances)
	}
	totalNHs := cfg.NumNexthopGroup * cfg.NumNexthopPerNHG
	if totalNHs%cfg.NumNetworkInstances != 0 {
		return nil, fmt.Errorf("total NHs (%d * %d = %d) must be divisible by NumNetworkInstances (%d)", cfg.NumNexthopGroup, cfg.NumNexthopPerNHG, totalNHs, cfg.NumNetworkInstances)
	}

	// 2. Initialize
	allEntries := []fluent.GRIBIEntry{}
	// Calculate per-NI counts
	numPrefixesPerNI := cfg.NumPrefixes / cfg.NumNetworkInstances
	numNHGsPerNI := cfg.NumNexthopGroup / cfg.NumNetworkInstances
	numNHsPerNI := totalNHs / cfg.NumNetworkInstances
	numNHsPerGroup := cfg.NumNexthopPerNHG

	// 3. Loop through Network Instances
	for niIndex := 0; niIndex < cfg.NumNetworkInstances; niIndex++ {
		var niName string
		if niIndex == 0 {
			// The first instance (index 0) is always DEFAULT
			niName = fakedevice.DefaultNetworkInstance
		} else {
			// Subsequent instances use BaseName-1, BaseName-2, ... (using niIndex as the 1-based suffix)
			niName = fmt.Sprintf("%s-%d", cfg.NetworkInstanceBaseName, niIndex)
		}

		// Calculate offsets for global uniqueness based on per-NI counts
		nhIndexOffset := uint64(niIndex * numNHsPerNI)
		nhgIDOffset := uint64(niIndex * numNHGsPerNI)

		// Generate entries for this NI using per-NI counts
		nhs, err := cfg.populateNextHops(niIndex, numNHsPerNI, nhIndexOffset)
		if err != nil {
			return nil, fmt.Errorf("failed to populate next hops for NI %s (index %d): %w", niName, niIndex, err)
		}
		allEntries = append(allEntries, nhs...)

		nhgs, err := cfg.populateNextHopGroups(numNHGsPerNI, numNHsPerGroup, nhgIDOffset, nhIndexOffset)
		if err != nil {
			return nil, fmt.Errorf("failed to populate next hop groups for NI %s (index %d): %w", niName, niIndex, err)
		}
		allEntries = append(allEntries, nhgs...)

		prefixEntries, err := cfg.populatePrefixes(niName, numPrefixesPerNI, numNHGsPerNI, nhgIDOffset)
		if err != nil {
			return nil, fmt.Errorf("failed to populate prefixes for NI %s (index %d): %w", niName, niIndex, err)
		}
		allEntries = append(allEntries, prefixEntries...)
	}

	return allEntries, nil
}
